# This file was generated by GoReleaser. DO NOT EDIT.
cask "archdoc" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/archdoc"]
    end
  end

  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "70bdf34bcf2b1bd817573688d0df3b7a408e5f19112c440e04b427b773f5dfc3"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "613d5acafa40d369840e16f158533ff22bade983c87e60ad5a83f27d3ba52ae2"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "15c8074975cf72ba6f719c474d077aae8f30000667f394f7f6a05da6cb866e67"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "49f4669397d16430f039e52467882367591ac3b5d43dc958f95551ee2cdcf139"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "archdoc"
  desc "Manage a specification repository of RFCs, ADRs, spec pages and refs"
  homepage "https://github.com/archdochq/archdoc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "archdoc"

  # No zap stanza required
end
