# This file was generated by GoReleaser. DO NOT EDIT.
cask "archdoc" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/archdoc"]
    end
  end

  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "8bb3515cc7815a07b6966e8ec467163309f0cdf8991ca0ff7d7b45f6a3f184b0"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5c0f522396a2ae9a343a6d9c9467f0d62ef9c18500df1a3562f77a2cbfd33bd8"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cfce996f79912ef8e364ecf4a6f077616b9a9025ed399d8b816a6e65cf6ce8bc"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca85c157b8f0397007d3d0584dd2a147b1c303d70e8b2d492ab15353356b185d"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "archdoc"
  desc "Manage a specification repository of RFCs, ADRs, spec pages and refs"
  homepage "https://github.com/archdochq/archdoc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "archdoc"

  # No zap stanza required
end
