# This file was generated by GoReleaser. DO NOT EDIT.
cask "archdoc" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/archdoc"]
    end
  end

  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "46628627c8472cbd1f7ab3165ac2c25f974a7b991cc47b1b8da6e688208d90f6"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b367318fc76050d653cb28d84be99eb270d09c49c40d44349afd060c8a61a0b2"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d4908ebcd2467da4bad112077719166d04e5b102642f44d7c2fadbd0b6648d1b"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b50b903b4699d74193946213736f384f400c1e19a81ebfbbee29b6b09e546f9f"
      url "https://github.com/archdochq/archdoc/releases/download/v#{version}/archdoc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "archdoc"
  desc "Manage a specification repository of RFCs, ADRs, spec pages and refs"
  homepage "https://github.com/archdochq/archdoc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "archdoc"

  # No zap stanza required
end
